#!/usr/bin/env bash


export KSCRIPT_DSL_HEADER='
@file:DependsOn("de.mpicbg.scicomp:kutils:0.4")

// make sure to also support includes in here


@file:Include("util.kt")

@file:KotlinOpts("-J-Xmx5g")


// define some important object used throughout the dsl
val foo = "bar"
'

kscript $@