#!/usr/bin/env bash


## resolve application jar path from script location and convert to windows path when using cygwin
jarPath=$(dirname $0)/kscript.jar
if [[ $(uname) == CYGWIN* ]]; then jarPath=$(cygpath -w ${jarPath}); fi

## run it using command substitution to have just the user process once kscript is done
exec $(kotlin -classpath ${jarPath} kscript.app.KscriptKt "$@")
