#!/bin/bash

### auto-install mvncp for automatic dependency resolution if not yet present
if [ -z "$(which mvncp)" ]; then
    curl -s https://raw.githubusercontent.com/holgerbrandl/kscript/master/mvncp > ~/bin/mvncp && chmod u+x ~/bin/mvncp
fi


#dependencies=$DEPS
dependencies=$(grep -F "//DEPS" $1 | head -n1 | cut -f2 -d' ' | tr ',' ' '  )
#dependencies=$(grep -F "//DEPS" $1 | cut -f2 -d' ' | tr ',' ' '  )
#dependencies=" org.docopt:docopt:0.6.0-SNAPSHOT log4j:log4j:1.2.14 "
#echo "dependencies are $dependencies"

if [ -n "$dependencies" ]; then
    classpath=$(mvncp ${dependencies} | grep -v outer)
    if [ -n "$(echo $classpath | grep ERROR)" ]; then echo "$classpath" >&2; exit; fi
#    classpath=$(mvncp $(echo "$DEPS" | tr ',' " " | tr -d '"') 2>/dev/null)
fi
#shift

## directly run the script...
#echo kotlinc -script -classpath "$classpath" "$@"

## ... or use a cached version of it if possible
#scriptFile="./test.kts"
#scriptFile="./mein_test.kts"
scriptFile=$1
shift

## work around missing md5sum on mac
if [ "${OSTYPE//[0-9.]/}" == "darwin" ]; then md5sum(){ md5 -r $1; }; fi

#jarFile=$(pwd)/${scriptFile%%.kts}.jar
scriptCheckSum=$(md5sum ${scriptFile} | awk '{ print $1 }')
scriptCheckSum=${scriptCheckSum:0:6}

jarFile=$(pwd)/.$(basename ${scriptFile} .kts).${scriptCheckSum}.jar


## capitalize first letter (since this is what kotlin compiler is doing for the wrapper
className=$(basename ${scriptFile} .kts)
#className="${className^}" ## disabled because requires bash4 and thus not on macos
className=$(echo ${className:0:1} | tr  '[a-z]' '[A-Z]')${className:1}


# build cache-jar if it does not yet exist
if [ ! -f "${jarFile}" ]; then
    ## remove previous (now outdated) cache jars
    rm -f .$(basename ${scriptFile} .kts).*.jar

    kotlinc  -classpath "${classpath}" -d ${jarFile} ${scriptFile}

    mainJava=$(mktemp -dt kscript.XXXXXX)/Main_${className}.java

    echo '
    public class Main_'${className}' {
        public static void main(String... args) throws Exception {
            Class script = Main_'${className}'.class.getClassLoader().loadClass("'$className'");
            script.getDeclaredConstructor(String[].class).newInstance((Object)args);
        }
    }
    '> ${mainJava}

    javac ${mainJava}  2> /dev/null

    ## update the jar to include main-wrapper
    (cd $(dirname ${mainJava}) && jar uf ${jarFile}  $(basename ${mainJava%%.java}.class))
fi


## disabled since kotlin binary fails to add kotlin-stdb when using jar as sole argument
## update manifest to specify main class
#echo "Main-Class: Main_${className}" > ${mainJava}.manimain
#jar ufm ${jarFile} ${mainJava}.manimain
#jar tf ${jarFile}

exec kotlin -classpath ${jarFile}:"$classpath" Main_${className} "$@"
