#!/usr/bin/env bash


# version tag for backward compatibility with kscript v1.x
KSCRIPT_VERSION=2.0


exec $(kotlin -classpath ../../build/libs/kscript-0.1-SNAPSHOT-all.jar kscript.app.KscriptKt "$@")
