#!/usr/bin/env bash

exec $(kotlin -J-agentlib:jdwp=transport=dt_socket,server=n,address=scicomp-mac-12-usb.mpi-cbg.de:8765,suspend=y -classpath ../../kscript/build/libs/kscript-0.1-SNAPSHOT-all.jar kscript.app.KscriptKt "$@")
