#!/usr/bin/env bash


# version tag for backward compatibility with kscript v1.x
KSCRIPT_VERSION=2.0


## using shadow jar
#echo $(kotlin -classpath /Users/brandl/projects/kotlin/kscript/build/libs/kscript-0.1-SNAPSHOT-all.jar kscript.app.KscriptKt "$@")

## using simple jar
#kotlin -classpath /Users/brandl/projects/kotlin/kscript/build/libs/kscript-0.1-SNAPSHOT.jar kscript.app.KscriptKt "$@"

## todo inline jar

#exec $(kotlin -classpath /Users/brandl/projects/kotlin/kscript/build/libs/kscript-0.1-SNAPSHOT-all.jar kscript.app.KscriptKt "$@")
exec $(kotlin -J-agentlib:jdwp=transport=dt_socket,server=n,address=scicomp-mac-12-usb.mpi-cbg.de:8765,suspend=y -classpath ../../kscript/build/libs/kscript-0.1-SNAPSHOT-all.jar kscript.app.KscriptKt "$@")
