#!/usr/bin/env bash


# resolve own location
MYSELF=$(which "$0" 2>/dev/null)
[ $? -gt 0 -a -f "$0" ] && MYSELF="./$0"

exec $(kotlin -classpath $MYSELF kscript.app.KscriptKt "$@")
#echo "survived exec!"
