#!/usr/bin/env bash

absolute_path() {
    # if the given path to the kscript launcher is absolute (i.e. it is either starting with / or a
    # 'letter:/' when using gitbash on windows) it is returned unchanged, otherwise we construct an absolute path
    [[ $1 = /* ]] || [[ $1 =~ ^[A-z]:/ ]] && echo "$1" || echo "$PWD/${1#./}"
}

resolve_symlink() (
    if [[ $OSTYPE != darwin* ]]; then minusFarg="-f"; fi
    sym_resolved=$(readlink ${minusFarg} $1)

    if [[ -n $sym_resolved ]]; then
        echo $sym_resolved
    else
        echo $1
    fi
)

ABS_KSCRIPT_PATH=$(resolve_symlink $(absolute_path $0))

JAR_PATH=$(dirname "$ABS_KSCRIPT_PATH")/kscript.jar

## prefer KOTLIN_HOME instead of PATH to resolve `kotlin` location (see #145)
if [[ -z "$KOTLIN_HOME" ]]; then
  KOTLIN_BIN=""

  # see discussion on https://github.com/holgerbrandl/kscript/issues/15
  REGEXP="-Dkotlin\.home=([^ ]*)"
  GUESS_KOTLIN_HOME=$(KOTLIN_RUNNER=1 JAVACMD=echo kotlinc)

  if [[ $GUESS_KOTLIN_HOME =~ $REGEXP ]]; then
    KOTLIN_BIN="${BASH_REMATCH[1]}/bin/"
  fi
else
  KOTLIN_BIN="$KOTLIN_HOME/bin/"
fi

# OSTYPE can be: linux-gnu, freebsd, darwin, cygwin, msys
if [[ "$OSTYPE" == "cygwin" || "$OSTYPE" == "msys" ]]; then
  JAR_PATH=$(cygpath -w "${JAR_PATH}")
  true
fi

## expose the name of the script being run to the script itself
export KSCRIPT_FILE="$1"

## run it using command substitution to have just the user process once kscript is done
COMMAND=$("${KOTLIN_BIN}kotlin" -classpath "${JAR_PATH}" kscript.app.KscriptKt "$OSTYPE" "$@")
RESULT=$?

if [ ! $RESULT -eq 0 ]; then
    exit $RESULT
fi

if [ -n "$COMMAND" ]; then
    eval "exec $COMMAND"
fi
