import here.we.go
import we.go.here
import go.here.we
import if.not.now.when
import if.not.me.then.who
import my.cool.class
//DEPS com.eclipsesource.minimal-json:minimal-json:0.9.4

file 1

Lastly, she pictured to herself how this same little sister of
hers would, in the after-time, be herself a grown woman; and how
she would keep, through all her riper years, the simple and
loving heart of her childhood:  and how she would gather about
her other little children, and make THEIR eyes bright and eager
with many a strange tale, perhaps even with the dream of
Wonderland of long ago:  and how she would feel with all their
simple sorrows, and find a pleasure in all their simple joys,
remembering her own child-life, and the happy summer days.


file 2

Alice waited a little, half expecting to see it again, but it
did not appear, and after a minute or two she walked on in the
direction in which the March Hare was said to live.  `I've seen
hatters before,' she said to herself; `the March Hare will be
much the most interesting, and perhaps as this is May it won't be
raving mad--at least not so mad as it was in March.'  As she said
this, she looked up, and there was the Cat again, sitting on a
branch of a tree.

file 3
important to not treat me as import

This time Alice waited patiently until it chose to speak again.
In a minute or two the Caterpillar took the hookah out of its
mouth and yawned once or twice, and shook itself.  Then it got
down off the mushroom, and crawled away in the grass, merely
remarking as it went, `One side will make you grow taller, and
the other side will make you grow shorter.'


Script
important to also not treat me as import

Alice was beginning to get very tired of sitting by her sister
        on the bank, and of having nothing to do:  once or twice she had
peeped into the book her sister was reading, but it had no
pictures or conversations in it, `and what is the use of a book,'
thought Alice `without pictures or conversation?'

