#!/usr/bin/env kscript
//DEPS com.eclipsesource.minimal-json:minimal-json:0.9.4
//INCLUDE file1
//INCLUDE file2
//INCLUDE file3

import my.cool.class

Script
important to also not treat me as import

Alice was beginning to get very tired of sitting by her sister
        on the bank, and of having nothing to do:  once or twice she had
peeped into the book her sister was reading, but it had no
pictures or conversations in it, `and what is the use of a book,'
thought Alice `without pictures or conversation?'